version: "3.3"
services:
  nodeserver:
    build:
      context: .
    image: tocos-backend
    ports:
      - "8000:8000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
